#! /bin/bash
printf '%s\n' "$(date), $(tput bold)${BASH_SOURCE[0]}$(tput sgr0)"

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-proc-topfiles#s2-proc-buddyinfo
# ome of the more useful virtual files in the top-level of the /proc/ directory

# if [ -f  /proc/cpuinfo ] tested in info.sh

function proc_probes(){
    # ${1}: "buddyinfo"
    # ${2}: "used primarily for diagnosing memory fragmentation issues"
    safe=$(echo "${1}" | tr / -)
    #export my_log="${dirProc}/proc-${safe}.txt"
    #echo "calling proc_probes_tasker"
    #echo "\${1} = ${1}; \${2} = ${2}; \${3} = ${3};"

    proc_probes_tasker "${1}" "${2}" "proc-${safe}.txt"
}

function proc_probes_tasker(){
    #echo "inside proc_probes_tasker"
    #echo "\${1} = ${1}; \${2} = ${2}; \${3} = ${3}"
    write_proc_probes "${1}" "${2}" "${dirProc}/${3}"
    write_proc_probes "${1}" "${2}" "${locker}/proc/${3}"
}
function write_proc_probes (){
    write_standard_header "proc-${safe}"    ${3}
    echo "cat /proc/${1} for ${moniker}" >  ${3}
    echo "${2}"                          >> ${3}
    echo ""                              >> ${3}
    echo "/proc/${1}:"                   >> ${3}
    cat  "/proc/${1}"                    >> ${3} 2>&1
}

alias cpu_out="grep -i 'model name' /proc/cpuinfo | sort | uniq"
export my_log="${locker}/cpu-basics.txt"
echo "grep -i 'model name' /proc/cpuinfo | sort | uniq" >  ${my_log}
      grep -i 'model name' /proc/cpuinfo | sort | uniq  >> ${my_log}

#rm -rf ${id}/proc-*.txt
export dirProc="${HOME}/.info/proc-filesystem"
mkdir -p "${dirProc}"

proc_probes "buddyinfo"   "used primarily for diagnosing memory fragmentation issues"                 &
proc_probes "cmdline"     "parameters passed to the kernel when it is started"                        &
proc_probes "cpuinfo"     "type of processor used"                                                    &
proc_probes "crypto"      "lists all installed cryptographic ciphers used by the Linux kernel"        &
proc_probes "devices"     "displays the various character and block devices currently configured"     &
proc_probes "driver"      "information for specific drivers in use by the kernel"                     &
proc_probes "dma"         "registered ISA DMA channels in use"                                        &
proc_probes "execdomains" "execution domains currently supported by the Linux kernel,"                &
proc_probes "fb"          "frame buffer devices"                                                      &
proc_probes "filesystems" "file system types currently supported by the kernel"                       &
proc_probes "interrupts"  "the number of interrupts per IRQ on the x86 architecture"                  &
proc_probes "iomem"       "current map of the system's memory for each physical device"               &
proc_probes "ioports"     "currently registered port regions used for input or output communication"  &
proc_probes "kmsg"        "messages generated by the kernel"                                          &
proc_probes "loadavg"     "load average in regard to both the CPU and IO over time"                   &
proc_probes "locks"       "files currently locked by the kernel"                                      &
proc_probes "mdstat"      "current information for multiple-disk, RAID configurations"                &
proc_probes "meminfo"     "valuable information about the system's RAM usage"                         &
proc_probes "misc"        "miscellaneous drivers registered on the miscellaneous major device, which is device number 10"  &
proc_probes "modules"     "all modules loaded into the kernel"                                        &
proc_probes "mounts"      "all mounts in use"                                                         &
proc_probes "mtrr"        "current Memory Type Range Registers (MTRRs) in use with the system"        &
proc_probes "partitions"  "partition block allocation information"                                    &
proc_probes "scsi/scsi"   "list of every recognized SCSI device"                                      &
proc_probes "slabinfo"    "full information about memory usage on the slab level"                     &
proc_probes "stat"        "statistics about the system since last restart"                            &
proc_probes "slabinfo"    "full information about memory usage on the slab level"                     &
proc_probes "swaps"       "measures swap space and its utilization"                                   &
proc_probes "uptime"      "uptime since restart"                                                      &
proc_probes "slabinfo"    "full information about memory usage on the slab level"                     &
proc_probes "version"     "version of the Linux kernel, gcc version used to compile the kernel, time of kernel compilation, kernel compiler's user name "  &

# # special cases
export my_log="${dirProc}/proc-panic-oom.txt"
write_standard_header "${core}/info-panic-oom.txt"    ${my_log}
echo "cat /proc/sys/vm/panic_on_oom"               >> ${my_log}
      cat /proc/sys/vm/panic_on_oom                >> ${my_log} 2>&1

# export dirHere=$(pwd)
# cd /proc/bus
# for i in *; do
#     cat
# done
# ls -alh /proc/bus > ${id}/proc-filesystem/proc-bus-dir.txt
